practiceproject/firstapp/urls.py
from django.urls import path
from firstapp import views

app_name = 'firstapp'
urlpatterns = [
    path("",views.index,name = "index" ),

    path('addmusician/',views.musician_form, name = 'musicianform'),
    path('addalbumb/', views.albumb_form, name='albumbform'),
    path('albumblist<int:artist_id>/',views.albumb_list,name='albumblist'),
    path('edit_artist<int:artist_id>/',views.edit_artist,name='edit_artist'),
    path('edit_albumb<int:albumb_id>/',views.edit_albumb, name='edit_albumb'),
    path('delete_albumb<int:albumb_id>/',views.delete_albumb, name='delete_albumb'),
    path('delete_artist<int:artist_id>/',views.delete_artist, name='delete_artist'),


    
]
 

practiceproject/practiceproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/',include('firstapp.urls')),
]

practiceproject/firstapp/models.py
from django.db import models

# Create your models here.

class Musician(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    instrument = models.CharField(max_length=500)
    
    def __str__(self) :
        
        return self.first_name + " "+ self.last_name
        
    

class Album(models.Model):
    artist = models.ForeignKey(Musician, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    relase_date = models.DateField()
    
    rating = (
        (1, "worst"),
        (2,'good'),
        (3, 'better'),
        (4,'best'),
        (5,'Excellent'),
    )
    nums_strs = models.IntegerField(choices=rating)
    
    def __str__(self):
        return self.name + " Rating : "+ str(self.nums_strs)
    

practiceproject/firstapp/forms.py
from django import forms
from django.core import validators

from firstapp import models


class MusicianForm(forms.ModelForm):

    class Meta:
        model = models.Musician
        
        fields = "__all__"
        



class AlbumbForm(forms.ModelForm):
    relase_date  = forms.DateField(widget= forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model = models.Album
        fields = "__all__"
    

practiceproject/firstapp/views.py
from django.shortcuts import render, get_object_or_404

from firstapp import forms

from firstapp import models
from django.db.models import Avg


def index(request) :
    musician_list = models.Musician.objects.order_by('first_name')
    
    diction = {'title':'Home page',"musician_list":musician_list}
    
    return render(request, 'firstapp/index.html', context = diction)
             

def albumb_list(request, artist_id):
    musician_info = models.Musician.objects.get(pk=artist_id)
    albumb_list = models.Album.objects.filter(artist_id=artist_id).order_by('name','relase_date')
    artist_rating = models.Album.objects.aggregate(Avg('nums_strs'))
    diction = {'title' : 'albumb_list' , 'musician_info':musician_info, 'albumb_list':albumb_list,"artist_rating":artist_rating}
    return render(request, 'firstapp/albumblist.html' ,context=diction)

def musician_form(request):
    new_form = forms.MusicianForm()
    
    diction = {'title':'Add Musician', 'new_form': new_form}
    
            
    if request.method == "POST":
        new_form = forms.MusicianForm(request.POST)
                   
        if new_form.is_valid():
            
            new_form.save(commit=True)
            return index(request)
            
    return render(request, 'firstapp/musicianform.html', context=diction)

def albumb_form(request):
    new_form = forms.AlbumbForm()
    
    diction = {'title': 'Add alabumb' ,"new_form":new_form}
    
    if request.method == "POST":
        new_form = forms.AlbumbForm(request.POST)
        new_form.save(commit=True)
        return index(request)
            
    
    return render(request,'firstapp/alabumform.html',context=diction)
    

def edit_artist(request,artist_id):
    artist_info = models.Musician.objects.get(pk=artist_id)
    form = forms.MusicianForm(instance=artist_info)
   
    if request.method == "POST":
        form = forms.MusicianForm(request.POST,instance=artist_info)
        
        if form.is_valid():
            form.save(commit=True)
            return albumb_list(request,artist_id)
    diction = {'form':form, 'artist_id':artist_id}
    return render(request, 'firstapp/edit_artist.html',context=diction)

def edit_albumb(request, albumb_id):
    albumb_info = models.Album.objects.get(pk=albumb_id) 
    form = forms.AlbumbForm(instance=albumb_info)
    diction = {'edit_form': form}
    if request.method == "POST":
        form = forms.AlbumbForm(request.POST,instance=albumb_info)  # Correctly pass request.POST and request.FILES
        if form.is_valid():
            form.save(commit=True)
            diction.update({"success_text": "Successfully updated", "edit_form": form})
            
        
    
    diction.update({'albumb_id':albumb_id})
    
    
    return render(request, 'firstapp/edit_albumb.html', context=diction)

def delete_albumb(request, albumb_id):
    albumb = models.Album.objects.get(pk=albumb_id).delete()
    diction = {"delete_message":"Albumb delete Sucessfully"}
    
    return render(request,'firstapp/delete.html',context=diction)

def delete_artist(request, artist_id):
    artist = models.Musician.objects.get(pk=artist_id).delete()
    diction = {"delete_message": "Artist delete successfully"}
    
    return render(request, 'firstapp/delete.html',context=diction)

practiceproject/templates/firstapp/alabumform.html
{% extends 'firstapp/base.html' %}
{% load static %}



{% block block_body %}
<h3>Albumb Form </h3>
 <form action="" method="POST" >
    {% csrf_token %}
    {{new_form.as_p}}
    <input type="submit" name="submit" value="Add" class="btn btn-primary btn-sm">
 </form>
{% endblock block_body %}
    

practiceproject/templates/firstapp/albumblist.html
{% extends 'firstapp/base.html' %}
{% load static %}



{% block block_body %}



<h1>Artist Informations</h1>
<h4>Artist Name: {{musician_info.first_name}} {{musician_info.last_name}}<h4> 
<h4>Instrument: {{musician_info.instrument}}</h4>
<h4>Rating: {{artist_rating.nums_strs__avg}}</h4>

<a href="{% url 'firstapp:edit_artist' artist_id=musician_info.id %}" class="btn btn-success btn-sm">Edit</a>

<h1>Albumb List</h1>


<table class = "table table-borderd" >
    <tr>
        <th>Artist</th>
        <th>Albumb_Name</th>
        <th>Relase Date</th>
        <th>Rating</th>
    </tr>
    
    {% for item in albumb_list %}
     
        <tr>
            <td><a href="{% url 'firstapp:edit_albumb' albumb_id=item.id %}">{{item.artist}}</a></td>
            <td><a href="{% url 'firstapp:edit_albumb' albumb_id=item.id %}">{{item.name}}</a></td>
            <td><a href="{% url 'firstapp:edit_albumb' albumb_id=item.id %}">{{item.relase_date | date:'M d, Y'}}</a></td>
            <td><a href="{% url 'firstapp:edit_albumb' albumb_id=item.id %}">{{item.nums_strs}}</a></td>
        </tr>
    {% endfor %}
        
</table>

{% endblock block_body %}
    

practiceproject/templates/firstapp/base.html
<!doctype html>
<html lang="en">
    <head>
        <title>
            
            {{title}}
        </title>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />

        <!-- Bootstrap CSS v5.2.1 -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />
        
        {% block css %}
            
        {% endblock css %}
            
    </head>

    <body>
     
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Navbar</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'firstapp:index' %}">Home Page</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'firstapp:musicianform' %}">Add Musician</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'firstapp:albumbform' %}">Add Albumb</a>
                  </li>
               
                    
                
              </div>
            </div>
          </nav>

          
        <div class="container">
            {% block block_body %}
                
            {% endblock block_body %}
        </div>
            
         
                
       
    </body>
</html>

practiceproject/templates/firstapp/delete.html
{% extends 'firstapp/base.html' %}

{% block block_body %}

<div class="alert alert-danger">
    {{delete_message}}
</div>

{% endblock block_body %}

practiceproject/templates/firstapp/edit_albumb.html
{% extends 'firstapp/base.html' %}

{% block block_body %}

<h1>Edit Albumb Page</h1>
 {% if success_text %}
 <div class="alert alert-success">
    {{success_text}}
</div>
 {% endif %}
<form action="" method="POST">
    {% csrf_token %}
    {{edit_form.as_p}}
    <input type="submit" name="submit" value = "Update" class = "btn btn-info btn-sm">
</form>
<br>
<a href="{% url 'firstapp:delete_albumb' albumb_id=albumb_id %}" class = 'btn btn-danger btn-sm' onclick = "return confirm('Are you sure to delate?')">Delete</a>
{% endblock block_body %}

practiceproject/templates/firstapp/edit_artist.html
{% extends 'firstapp/base.html' %}


{% block block_body %}
 <h2>Edit page</h2>
  
 <form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input class="btn btn-info btn-sm" type="submit" name="submit" value="Update">
 </form> <br>
 <a href=" {% url 'firstapp:delete_artist' artist_id=artist_id  %}" class = "btn btn-danger btn-sm" onclick = "return confirm('Are you sure to delate?')">Delete</a>
    
{% endblock block_body %}
    

practiceproject/templates/firstapp/form.html
{% extends 'firstapp/base.html' %}
{% load static %}

{% block title %}
    Add musician
{% endblock title %}


{% block css %}
   <link rel="stylesheet" href="{% static 'css/firstapp/form.css' %}"> 
{% endblock css %}
    

{% block block_body %}
<h1>{{text}}</h1>
<form action="" method="post">
    {% csrf_token %}
    {{new_form.as_p}}
    <input type="submit" value = "Submit">
</form>
{% endblock block_body %}
    

practiceproject/templates/firstapp/index.html
{% extends 'firstapp/base.html' %}
{% load static %}



{% block block_body %}
  
  
  {% if musician_list %}
   <h3>Musician list</h3>
    
    {% for item in musician_list %}
        <ul>
            <a href="{% url 'firstapp:albumblist' artist_id=item.id %}">
                <li>{{item.first_name}} {{item.last_name}}</li></a>
        </ul>
    {% endfor %}
        
  {% else %}
    <h3>No Musician is Available now!</h3>
  {% endif %}
    
    

{% endblock block_body %}
    

practiceproject/templates/firstapp/musicianform.html
{% extends 'firstapp/base.html' %}
{% load static %}



{% block block_body %}
<h3>Musician Form</h3>
 <form action="" method="POST" >
    {% csrf_token %}
    {{new_form.as_p}}
    <input type="submit" name="submit" value="Add" class="btn btn-primary btn-sm">
 </form>

{% endblock block_body %}
    